---
version: '3.8'
services:
  bouncer-mikrotik-dev:
    container_name: bouncer-mikrotik-dev
    image: quay.io/kaszpir/cs-mikrotik-bouncer-alt:v0.7.0 # unreleased v0.7.0
    env_file: ".env"
    ports:
      - 2112:2112/tcp # default metrics port
      - 40000:40000/tcp # https://ko.build/features/debugging/
    read_only: true
    restart: unless-stopped
    privileged: false
    cap_drop:
      - ALL


  prometheus:
    image: quay.io/prometheus/prometheus
    # network_mode: host #comment this out and uncomment ports
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml:ro"

  grafana:
    image: grafana/grafana
    # network_mode: host #comment this out and uncomment ports
    ports:
      - "3000:3000"
    volumes:
      - "./grafana/dashboards/:/var/lib/grafana/dashboards/:ro"
      - "./grafana/provisioning/:/etc/grafana/provisioning/:ro"
