---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: crowdsec
resources:

  - deployment.yaml
  - service.yaml
  # - serviceMonitor.yaml

secretGenerator:
  - name: bouncer-mikrotik
    envs:
      - .env
images:
  - name: quay.io/kaszpir/cs-mikrotik-bouncer-alt
    newTag: v0.8.0
